services:
  api-id:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    image: api-id-development:latest
    container_name: api-id-development
    platform: ${SERVER_PLATFORM}
    ports:
      - "3002:3000"
    environment: # This configuration can override the settings in the Dockerfile.
      - PORT=3000
      - HOST_IP=${HOST_IP}
    volumes:
      - ../../logs:/app/logs
    command: ["npm", "run", "start:dev"] # Also can override the settings in the Dockerfile.
